/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BookingsIdRouteImport } from './routes/bookings/$id'
import { Route as BookingsNewRouteImport } from './routes/bookings/new'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as LocationsIdRouteImport } from './routes/locations/$id'
import { Route as LocationsNewRouteImport } from './routes/locations/new'
import { Route as LocationsShareRouteImport } from './routes/locations/share'
import { Route as ShareShareIdRouteImport } from './routes/share/$shareId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNewRoute = LocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsShareRoute = LocationsShareRouteImport.update({
  id: '/locations/share',
  path: '/locations/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/bookings/new': typeof BookingsNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/locations/share': typeof LocationsShareRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/bookings/new': typeof BookingsNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/locations/share': typeof LocationsShareRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/settings': typeof SettingsRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/bookings/new': typeof BookingsNewRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/locations/share': typeof LocationsShareRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/settings'
    | '/bookings/$id'
    | '/bookings/new'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/share'
    | '/share/$shareId'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/settings'
    | '/bookings/$id'
    | '/bookings/new'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/share'
    | '/share/$shareId'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/settings'
    | '/bookings/$id'
    | '/bookings/new'
    | '/locations/$id'
    | '/locations/new'
    | '/locations/share'
    | '/share/$shareId'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  SettingsRoute: typeof SettingsRoute
  BookingsIdRoute: typeof BookingsIdRoute
  BookingsNewRoute: typeof BookingsNewRoute
  LocationsIdRoute: typeof LocationsIdRoute
  LocationsNewRoute: typeof LocationsNewRoute
  LocationsShareRoute: typeof LocationsShareRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/new': {
      id: '/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof LocationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/share': {
      id: '/locations/share'
      path: '/locations/share'
      fullPath: '/locations/share'
      preLoaderRoute: typeof LocationsShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  SettingsRoute: SettingsRoute,
  BookingsIdRoute: BookingsIdRoute,
  BookingsNewRoute: BookingsNewRoute,
  LocationsIdRoute: LocationsIdRoute,
  LocationsNewRoute: LocationsNewRoute,
  LocationsShareRoute: LocationsShareRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
